'use strict';

module.exports = [
  'channelCreate',
  'channelDelete',
  'channelPinsUpdate',
  'channelUpdate',
  'debug',
  'disconnect',
  'error',
  'guildBanAdd',
  'guildBanRemove',
  'guildCreate',
  'guildDelete',
  'guildMemberAdd',
  'guildMemberAvailable',
  'guildMemberRemove',
  'guildMembersChunk',
  'guildMemberSpeaking',
  'guildMemberUpdate',
  'guildRoleCreate',
  'guildRoleDelete',
  'guildRoleUpdate',
  'guildUnavailable',
  'guildUpdate',
  'message',
  'messageDelete',
  'messageDeleteBulk',
  'messageUpdate',
  'presenceUpdate',
  'ready',
  'reconnecting',
  'typingStart',
  'typingStop',
  'userUpdate',
  'voiceStateUpdate',
  'warn',
];
